version: 2.1

jobs:
  hello-world:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo 'Hello world from module beta! :3'

workflows:
  beta:
    jobs:
      - hello-world
