setup: true

version: 2.1

orbs:
  dynamic: bjd2385/dynamic-continuation@3.7.0

parameters:
  force-all:
    type: boolean
    default: false

jobs:
  hello-world:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    parameters:
      type: string
      default: ""
    steps:
      - checkout # check out the code in the project directory
      - run: echo 'Hello world from module << parameters.name >>!'

workflows:
  on-commit:
    jobs:
      - dynamic/continue:
          context: circleci
          auto-detect: true
          root-config: root
          force-all: << parameters.force-all >>
